### ISSUE TITLE
@route_cors(allow_origin="*",allow_methods=["GET"]) doesn't let request threw

### ISSUE THREAD

**Issue by bestben100** [pgjones/quart-cors#3]
This is my javascript

```
`fetch("https://discord.com/d", {method : "GET"})
.then(function(response) {
    console.log(response)
})`
```

But even with `@route_cors(allow_origin="*",allow_methods=["GET"]`) doesn't let request threw over my function
it gives me this error

```transcripts:1 Access to fetch at 'https://discord.com/d' from origin 'http://127.0.0.1:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```

**Comment by pgjones** [comment]
This library only allows you to set CORS headers for the endpoints you control. Given the error I don't think you control discord.com so it won't make any difference.
